version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: serialize-error
    versions:
    - 8.0.1
  - dependency-name: clipboard
    versions:
    - 2.0.7
